// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqyudhoxzutrybcilluq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxeXVkaG94enV0cnliY2lsbHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTM3NDIsImV4cCI6MjA1ODgyOTc0Mn0.3trVKQdjFVQTolBBpXmK3YuGjj1CEgOSQfPQdHFy-Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);